!function(e){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=e();else if("function"==typeof define&&define.amd)define([],e);else{var f;"undefined"!=typeof window?f=window:"undefined"!=typeof global?f=global:"undefined"!=typeof self&&(f=self),f.lfpGraph=e()}}(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(_dereq_,module,exports){
/* Generated by es6-transpiler 0.7.14-2 */ 
"use strict";

var Node = _dereq_('./node');

var LfpGraph = (function(){var DP$0 = Object.defineProperty;

  function LfpGraph(ctor) {var options = arguments[1];if(options === void 0)options = {};var id = arguments[2];if(id === void 0)id = null;
    if (!(this instanceof LfpGraph)) return new LfpGraph(ctor, options, id);
    
    this.nodes = {};
    this.typeCount = {};
    this.rootNode = null;

    var node = new Node(this, ctor(options));
    
    this.add(null, node, id);
  }DP$0(LfpGraph, "prototype", {"configurable": false, "enumerable": false, "writable": false});

  // adds a node to the structure
  LfpGraph.prototype.add = function(parent, node) {var id = arguments[2];if(id === void 0)id = null;
    id = id || node.lfp.type;
    this.typeCount[id] = this.typeCount[id] +1 || 0;
    id = (this.typeCount[id] === 0)? id : (("" + id) + ("-" + (this.typeCount[id])) + "");
    node.id = id; // to remove the node later

    if(parent){ // && this.nodes[parent.id]) {
      // debugging
      if(!this.nodes[parent.id]) console.error('Parent didnt register correctly');

      // fetch parent node
      var p = this.get(parent.id);

      // add node as nodes in the graph
      p.nodes.push(node.id);
      
      // removing logic, clean up when code is ready
      // node.parent = p.lfp; // bind the parnt for removing later
      // node.index = idx; // necessary?
    
    } else {
      this.rootNode = id;
    }

    this.nodes[node.id] = node;

    // console.log(this.nodes);
    return id;
  }

  // removes a node from the structure
  LfpGraph.prototype.remove = function(item) {var this$0 = this;

    // clear nodes nodes from the node
    // remove nodes from the graph

    // only if it has nodes
    if(item.nodes.length > 0) {
      
      // subnodes
      item.nodes.forEach(function(id ) {
        var node = this$0.get(id);
        this$0.remove(node); // remove subnodes
        delete this$0.nodes[id];
      });

      item.nodes = []; // reset nodes container
    }
  }

  // graph pipe, only adds nodes into the rootNode
  LfpGraph.prototype.pipe = function(ctor) {var options = arguments[1];if(options === void 0)options = {};var id = arguments[2];if(id === void 0)id = null;
    var lfp = ctor(options);
    var node = new Node(this, lfp);
   
    var parent = this.get(this.rootNode);
    parent.lfp.add(lfp);
    this.add(parent, node, id);

    return node;
  }

  LfpGraph.prototype.get = function(id) {
    return this.nodes[id];
  }


  LfpGraph.prototype.toString = function(){
    return this.nodes;
  }

;return LfpGraph;})();

module.exports = LfpGraph;
},{"./node":2}],2:[function(_dereq_,module,exports){
/* Generated by es6-transpiler 0.7.14-2 */ 
"use strict";

var Node = (function(){var DP$0 = Object.defineProperty;

  function Node(graph, lfp){
    this.graph = graph;
    this.lfp = lfp;
    this.nodes = [];
  }DP$0(Node, "prototype", {"configurable": false, "enumerable": false, "writable": false});

  Node.prototype.pipe = function(ctor) {var options = arguments[1];if(options === void 0)options = {};var id = arguments[2];if(id === void 0)id = null;
    var lfp = ctor(options);
    var nextNode = new Node(this.graph, lfp);
    
    this.lfp.add(lfp); // add to operators
    this.graph.add(this, nextNode, id); // add to graph: parent, child, id
    
    return nextNode;
  }

  Node.prototype.remove = function(){
    this.graph.remove(this);
    this.lfp.remove(this);
  }
;return Node;})();

module.exports = Node;
},{}]},{},[1])
(1)
});