/* Generated by es6-transpiler 0.7.14-2 */ 
"use strict";

var Node = (function(){var DP$0 = Object.defineProperty;

  function Node(graph, lfp){
    this.graph = graph;
    this.lfp = lfp;
    this.nodes = [];
  }DP$0(Node, "prototype", {"configurable": false, "enumerable": false, "writable": false});

  Node.prototype.pipe = function(ctor) {var options = arguments[1];if(options === void 0)options = {};var id = arguments[2];if(id === void 0)id = null;
    var lfp = ctor(options);
    var nextNode = new Node(this.graph, lfp);
    
    this.lfp.add(lfp); // add to operators
    this.graph.add(this, nextNode, id); // add to graph: parent, child, id
    
    return nextNode;
  }

  Node.prototype.remove = function(){
    this.graph.remove(this);
    this.lfp.remove(this);
  }
;return Node;})();

module.exports = Node;